language: android
jdk: oraclejdk8
#dist: trusty
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.5
    packages:
      - p7zip-full

cache:
  directories:
    - $HOME/cache


android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.2
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./travisndk.py
  - ./gradlew assembleRelease
  - ./gradlew test

licenses:
  - 'android-sdk-preview-license'
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'  
